### PR TITLE
Adding support for the SAV MK1

### PR DESCRIPTION
**Pull request by boelle**
Added at the end of the pins file as board number 888

### CODE REVIEW

**Comment by repetier** [comment]
I added the board to dev version and in online config tool thanks.

BTW: We only take commits against dev version, therefor I copied it by hand to it.

**Comment by boelle** [comment]
oki

wil try and remember that.

there might come a PR that adds support for an Oled board for the same controller

**Comment by repetier** [comment]
No problem. Just give it the next free controller number. I assigned board id 89 btw.

**Comment by boelle** [comment]
oki

its not a controller but a display :-D

**Pull request closed without merging**
