### PR TITLE
SKR E3 Mini: fix build failure & example config filenames

### PR DESCRIPTION
**Pull request by alexsomesan**
Currently the build for SKR E2 mini fails on Linux systems because the `src/Repetier/src/boards/STM32F1/boards/skr_mini_e3_v1_2/skr_startup_stm32f103xe.s` file having a lower-case extension.

It turns out PlatformIO cares about case on the extension when deciding which build tool will handle the file. Explained here: https://github.com/platformio/platform-ststm32/issues/332

Also renames `Configuration_io_Mini_E3.h` to align it to other SampleSystems entries.

### CODE REVIEW

**Comment by AbsoluteCatalyst** [comment]
Oh whoops, my bad on the Configuration_io_Mini_E3.h name. Forgot to rename it before I made the pull. Thanks!

**Comment by alexsomesan** [comment]
No worries, it was easy to spot and fix.

Thanks for putting together the sample configuration for at least one SKR. It's a huge progress boost for me in getting these boards to work with Repetier.

> Oh whoops, my bad on the Configuration_io_Mini_E3.h name. Forgot to rename it before I made the pull. Thanks!

**Comment by AbsoluteCatalyst** [comment]
Ah wait, you might want to merge with the latest dev2 and rebase this, repetier actually just pushed a commit fixing that same file extension lower-case issue just a few minutes ago. (He also moved the files to a new location)
I don't believe he fixed the samplesystem Configuration_io_Mini_E3 filename though. 
See: 5faf38150aaa9940e6452cf0ddfbcaa30aea5c94

**Comment by alexsomesan** [comment]
Can confirm 5faf381 fixes the startup code issue. I removed that change from this PR.

**Comment by AbsoluteCatalyst** [comment]
Sweet.

PS. If you happen to be running this on an ender 3, would you mind running a PID tune on the ender's bed heater and sharing the Kp Ki kD values?
I couldn't get ahold of anyone with one and I don't have that bed heater, so the sample's bed PID settings are wrong.

**Comment by alexsomesan** [comment]
Actually, I don't have an Ender 3 either. I plan to run it on a self-built HypercubeEvo (CoreXY). It has an MK42 bed.

**Comment by alexsomesan** [comment]
We could post a binary on the Ender 3 Facebook group in case someone wants to do the PID and contribute. Would also help with awareness about Repetier supporting these boards now.

**Comment by AbsoluteCatalyst** [comment]
I don't have a facebook account to post with, unfortunately. :( 
Great idea though, and I'd definitely like to increase more awareness for V2. I think creality recently got a discord too.  

I'll be adding another SKR E3 Mini V2.0 board variant sometime tonight or tomorrow since I got my hands on one. 
It's not too different. 

I do hope Repetier gets a chance to fix the invalid cert on the V2 doc site sometime soon. Chrome does it's big spooky warning.

**Comment by alexsomesan** [comment]
I'll post the binary to FB then, once I test the build to make sure all features of the board work.

I was just going through the https://docfirmwarev2.repetier.com site and Firefox is happy with it. It has a valid "Let's Encrypt" issued cert. Is that what you were referring to?

**Comment by AbsoluteCatalyst** [comment]
I believe it's because the cert was made for the docfirmwarev2 subdomain.
If you go directly to https://repetier.com/ instead you'll get the certificate error. (At least I do)

**Comment by alexsomesan** [comment]
WOW, yeah! You're right. It's still scary that way. 

I didn't notice it until now since I just followed the link from the top of README here on github.

**Comment by repetier** [comment]
Did not know repetier.com maps to that. Not planned. Correct url for docs is https://docfirmwarev2.repetier.com/ and there certificate is correct.

**Comment by AbsoluteCatalyst** [comment]
Oh I see, just noticed www.repetier.com links to your main site instead too. I saved the wrong url at some point. 
I'll update the v2 doc links I left inside the E3 sample configurations real quick.

**Pull request merged**
